### ISSUE TITLE
invalid type defs

### ISSUE THREAD

**Issue by trim21** [jkroso/parse-duration#59]
you didn't keep content of `index.d.ts` at https://github.com/jkroso/parse-duration/pull/58 so it break downstream typescript users

current `index.d.ts` doesn't provide any type info:

https://github.com/jkroso/parse-duration/blob/54a0fab7ec624f7ad1668a216e75e217878bf9d3/index.d.ts#L3-L4

**Comment by dy** [comment]
Thanks @trim21! Fixed in 2.0.2

**Comment by trim21** [comment]
https://github.com/jkroso/parse-duration/blob/51da6f41e6e8370986179979a8a41080ba0f1e74/test.js#L108

I think it's still wrong
